title: Muhammad Hamza Wahla # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  We have done a lot of GIS specified jobs like 
we had designed routing service and service area for a client from Malaysia in this project we had 3 cities SITWAN TAIPING  KAMPUNG we had been provided by the data of roads and cities, we performed NETWORK ANALYSIS on that data and discovered the span of traffic on the basis of distance and time 
<br><br>
"/images/image (3).png?raw=true"
<br><br>
 We had installed arcpy scripts in WEB ODM that performs conversion of DRONE images to DEM(digital elevation model) and 3D orientation scene
  <br><br>
  "/images/image (3).png?raw=true"
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
